<a href="https://colab.research.google.com/github/Shifa-parveen786/Data_Visualization/blob/main/ClassWork/NumpyInPython/3DArray.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [17]:
import numpy as np
x = np.zeros([3,6,2], dtype = 'int')
print(x)

[[[0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]]]
