<a href="https://colab.research.google.com/github/Shifa-parveen786/Data_Visualization/blob/main/ClassWork/NumpyInPython/OnesFunction(2DArray).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [18]:
import numpy as np
x = np.ones([4,3])
print(x)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
