<a href="https://colab.research.google.com/github/Shifa-parveen786/Data_Visualization/blob/main/ClassWork/NumpyInPython/OnesFunction(3DArray).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [20]:
import numpy as np
x = np.ones([3,5,1], dtype = 'int')
print(x)

[[[1]
  [1]
  [1]
  [1]
  [1]]

 [[1]
  [1]
  [1]
  [1]
  [1]]

 [[1]
  [1]
  [1]
  [1]
  [1]]]
