<a href="https://colab.research.google.com/github/Shifa-parveen786/Data_Visualization/blob/main/ClassWork/NumpyInPython/ZerosFunctionInInteger.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [16]:
import numpy as np
x = np.zeros([4,5], dtype = 'int')
print(x)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
